# Generated by Django 6.0.2 on 2026-07-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_subimages_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subimages',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
